### ISSUE TITLE
Cannot scan the Re-Verify Credential QR Code

### ISSUE THREAD

**Issue by RochelleBondoc** [verida/Credentials-Management-Platform#100]
**_URL:_** https://credentials.demos.verida.io/login

**_Steps to replicate:_** 

1. Go to https://credentials.demos.verida.io/login
2. Click the New Result button
3. Fill out the form
4. Click the Send Credential button
5. Inbox> Accept
6. Data> Credentials
7. Tap the copy icon
8. Copy the address
9. Paste the copied address on a browser
10. Verify that it opens Account Explorer> Credential Verification
11. Scan the Re-Verify Credential QR Code

**_Actual Result:_** Unable to scan the Re-Verify Credential QR Code URL: https://verida.network/credential?uri=dmVyaWRhOi8vZGlkOnZkYToweGZCMTAzMUNFRUFhNjk2OTljNDJhOTc0MTRGODQyM2IyMmQ4MkEyMzMvOENObVI1TDlZZGZBWW1mM2tYL2NyZWRlbnRpYWxfcHVibGljX2VuY3J5cHRlZC9mZDIyNDU5MC0wMzFkLTExZWQtYTZmMi02NWNiNDk1MGJkM2Y/a2V5PWIxZDIxYWNhYzEyYjc3YzU3NTk0YjdkM2YwM2E5YmI1NTAxNjc5OTZlZDljZDhlMmI0NTAyYmYzNTEyM2Y1ZmM=

**_Expected Result:_** User should be able to scan the QR code easily

![2022-07-14_11h01_51](https://user-images.githubusercontent.com/107521721/178888915-e572ba12-97a9-4f44-bc34-b879490b0c77.png)

![2022-07-14_11h01_58](https://user-images.githubusercontent.com/107521721/178888929-4d6a60d1-31e0-4dbc-ac87-2c9cc4d98045.png)

@cmcWebCode40 @andy-verida

**Comment by cmcWebCode40** [comment]
@RochelleBondoc, 

Please this issue is related to this here https://github.com/verida/demo-credential-issuer/issues/78 and has been resolved, will close this out.
