### ISSUE TITLE
Cannot accept credential created with new schema

### ISSUE THREAD

**Issue by NickDarvey** [verida/Credentials-Management-Platform#35]
I'm trying to add a new schema. Though this issue occurs within Verida Vault, I thought it likely is caused by something I'm doing here as other credential types work fine.

### Repro
1. Add a new schema via Schemas -> Add Schema. (e.g. [this schema](https://gist.githubusercontent.com/NickDarvey/aa55096620a22368a5c442f5eb913c6b/raw/ff351942113edeb5d3d00da8ed6489e0917a69d8/schema.json).)
1. Add the appropriate mapping to [map.js](https://github.com/verida/Credentials-Management-Platform/blob/develop/frontend/src/config/map.js)
   e.g. 
   ```js
   "https://schemas.primacy.co/work/accreditations/sg/work-at-height/v0.1.0/schema.json": {
      view: ["fullName", "nricFinWpNumber", "attainmentDate"],
      create: ["fullName", "nricFinWpNumber", "attainmentDate"],
    }
   ```
1. Run the app
1. Create a new result and send to a DID previously created with Verida Vault

### Expected

The credential is received in Verida Vault and can be accepted.

### Actual

The credential is received but cannot be accepted.
```
Error
Cannot accept data now
```
<details>
<img src="https://user-images.githubusercontent.com/6076697/153809913-34b11a31-8c67-4cb3-9dd9-5e1a56b471d2.png"/>
</details>

### System info

At this line
https://github.com/verida/Credentials-Management-Platform/blob/6f4017a875c25678706d5804176b147adc99f0ac/backend/src/helpers/VeridaHelper.ts#L160

the locals are:
```js
var response = {
  ok: true,
  id: 'd70b11d0-8d5b-11ec-9507-575595cb51a5',
  rev: '1-2762f2239a85f2d8e9b40e3ef996f0f8'
}

var data ={
  data: [
    {
      name: 'Work-at-height Accreditation',
      title: 'Work-at-height Accreditation',
      fullName: 'Nick Darvey',
      dateOfBirth: '2022-02-01',
      summary: 'New Work-at-height Accreditation test result is available',
      testTimestamp: '2022-02-14T06:03:28.229Z',
      schema: 'https://schemas.primacy.co/work/accreditations/sg/work-at-height/v0.1.0/schema.json',
      nricFinWpNumber: '123456',
      attainmentDate: '2022-02-14',
      didJwtVc: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJpYXQiOjE2NDQ4MTg2MTEsImV4cCI6bnVsbCwiYXVkIjoiZGlkOnZkYToweDIyM2NDMEU4ZGY3YmYyMDA5YzJiNTliMzk4Y2I4MDIwOEJEYUNiZTIiLCJkYXRhIjp7Im5hbWUiOiJXb3JrLWF0LWhlaWdodCBBY2NyZWRpdGF0aW9uIiwidGl0bGUiOiJXb3JrLWF0LWhlaWdodCBBY2NyZWRpdGF0aW9uIiwiZnVsbE5hbWUiOiJOaWNrIERhcnZleSIsImRhdGVPZkJpcnRoIjoiMjAyMi0wMi0wMSIsInN1bW1hcnkiOiJOZXcgV29yay1hdC1oZWlnaHQgQWNjcmVkaXRhdGlvbiB0ZXN0IHJlc3VsdCBpcyBhdmFpbGFibGUiLCJ0ZXN0VGltZXN0YW1wIjoiMjAyMi0wMi0xNFQwNjowMzoyOC4yMjlaIiwic2NoZW1hIjoiaHR0cHM6Ly9zY2hlbWFzLnByaW1hY3kuY28vd29yay9hY2NyZWRpdGF0aW9ucy9zZy93b3JrLWF0LWhlaWdodC92MC4xLjAvc2NoZW1hLmpzb24iLCJucmljRmluV3BOdW1iZXIiOiIxMjM0NTYiLCJhdHRhaW5tZW50RGF0ZSI6IjIwMjItMDItMTQifSwiY29udGV4dCI6IlZlcmlkYTogQ3JlZGVudGlhbCBNYW5hZ2VyIiwiaW5zZXJ0ZWRBdCI6IjIwMjItMDItMTRUMDY6MDM6MzEuNTE4WiIsImlzcyI6ImRpZDp2ZGE6MHgyMjNjQzBFOGRmN2JmMjAwOWMyYjU5YjM5OGNiODAyMDhCRGFDYmUyIn0.hvWKUfmzroYrVJfha8dqlEb_Wq93E1M_PZpcrKjZ7xTmk6NqaKDUZdidb-C3MBtifd1jiQouL0xPNtpYcEWGwg'
    }
  ]
}
```

**Comment by nick-verida** [comment]
I think this is now fixed

**Comment by nick-verida** [comment]
I think this is now fixed
