### ISSUE TITLE
Credential Details issues - No space in between Field Names, Repetitive word, Capitalized Case

### ISSUE THREAD

**Issue by RochelleBondoc** [verida/Credentials-Management-Platform#89]
**URL:** https://credentials.demos.verida.io/dashboard

**_Steps to replicate:_**

1. Go to https://credentials.demos.verida.io/dashboard
2. Select an Issued Test/Credential

**_Actual Result:_** 

- No space in between field names, (ie. "FullName:", "DateOfBirth:", "TestTimestamp:")
- Repetitive word  "Test Test" (ie. New COVID19 (PCR) _**Test Test**_ Result Is Available)
- Capitalized case (ie. New COVID19 (PCR) Test Test Result Is Available)

**_Expected Result:_** 

- Spelling issues should be fixed. 
- Remove the repetitive word
- Should use the correct case

![2022-07-14_07h14_31](https://user-images.githubusercontent.com/107521721/178855164-0d94135f-aa52-454d-870e-ea6898635fbe.png)

**Comment by cmcWebCode40** [comment]
@RochelleBondoc, 
 repetitive words are dynamic ( beeing supplied from the backend ).
