### ISSUE TITLE
Error when opening Schema URL for Hemoglobin Test and Syphilis (AB) Test

### ISSUE THREAD

**Issue by RochelleBondoc** [verida/Credentials-Management-Platform#90]
**_URL:_** https://credentials.demos.verida.io/dashboard

**_Steps to replicate:_**

1. Go to https://credentials.demos.verida.io/dashboard
2. Click the Schema tab
3. Click the schema Url for Haemoglobin Test: https://schemas.verida.io/health/pathology/tests/haemoglobin/v0.1.0/schema.json
4. Click the schema Url for Syphilis (AB) Test: https://common.verida.io/health/pathology/tests/syphilis/ab/v0.1.0/schema.json

**_Actual Result:_** Error when opening Schema URL for Hemoglobin Test and Syphilis (AB) Test
**_Expected Result:_** It should open the new tab without an error

![2022-07-14_07h27_25](https://user-images.githubusercontent.com/107521721/178857672-0efa9155-869a-42be-9be6-f95c8cdc815d.png)

https://www.loom.com/share/a1a82f6539de4a0b929bf69570d1b860

**Comment by cmcWebCode40** [comment]
@RochelleBondoc, 

i have deleted the schema write URL and updated with the correct URL, it works now
