### ISSUE TITLE
Schema - Misspelled word, Incorrect case

### ISSUE THREAD

**Issue by RochelleBondoc** [verida/Credentials-Management-Platform#91]
**URL:** https://credentials.demos.verida.io/dashboard

**Steps to replicate:**

1. Go to https://credentials.demos.verida.io/dashboard
2. Select Schema

**_Actual Result:_**

- Misspelled word "Haemoglobin Test"
- Incorrect case "schema Url :"

**_Expected Result:_** Words should be spelled as 'Hemoglobin Test' and 'Schema URL'

![2022-07-14_08h12_24](https://user-images.githubusercontent.com/107521721/178859431-f60a7d7f-4597-4511-bb8a-93fa2024f694.png)

**Comment by cmcWebCode40** [comment]
Resolved the `schema Url` case issue, but for the `Haemoglobin` word correction is supplied from the schema
