### ISSUE TITLE
Redundant field - Name and Title 

### ISSUE THREAD

**Issue by RochelleBondoc** [verida/Credentials-Management-Platform#92]
**_URL:_** https://credentials.demos.verida.io/dashboard

**_Steps to replicate:_**

1. Go to https://credentials.demos.verida.io/dashboard
2. Click Sent
3. Select an Issued Test/Credential

**_Actual Result:_** Name and Fields shows the same value

**_Expected Result:_**  The value for these fields is from the 'Document Type' field. Is this intentional? Shouldn't it just be displayed in a single field?

![2022-07-14_08h36_12](https://user-images.githubusercontent.com/107521721/178860108-e16a2e3d-833c-4c0f-9dba-b0dc72677080.png)

![2022-07-14_08h30_30](https://user-images.githubusercontent.com/107521721/178860118-9256a113-4197-4c81-bdff-e3b22dbd82a0.png)

**Comment by aurelticot** [comment]
`title` and `name` are two properties of the credential schema. Actually they are from the base schema, inherited by the credential schema.

`title` is the title of the message sent to the recipient
`name` is the name of the credential when displayed in the Vault

Given they have 2 purposes, we could challenge their values 
`name` could be "COVID-19 PCR test result"
`title` could be "New COVID-19 PCR test result available"

(To also define for the other types of credentials)

Additionally, we could challenge having the `title` displayed in this  "Credential Details" modal window

cc @cmcWebCode40 @RochelleBondoc
