### ISSUE TITLE
DidJwtVc is shown on the Credential Details for Australian Basic KYC and Cholesterol (Total) Test

### ISSUE THREAD

**Issue by RochelleBondoc** [verida/Credentials-Management-Platform#98]
**_URL:_** https://credentials.demos.verida.io/dashboard

**_Steps to replicate:_**

1. Go to https://credentials.demos.verida.io/dashboard
2. Click Sent
3. Select a Australian Basic KYC
4. Select a Cholesterol (Total) Test

**_Actual Result:_** 

- DidJwtVc is shown on the Credential Details for Australian Basic KYC and Cholesterol (Total) Test only
- It takes a lot of space on the Credential Details screen

**_Expected Result:_** It is only shown on two (2) results. Is it necessary to display it as it takes too much space on the screen?

![2022-07-14_10h27_31](https://user-images.githubusercontent.com/107521721/178885119-25e89675-d3ee-499c-8003-8c1473024f1c.png)

**Comment by aurelticot** [comment]
As a reference implementation / demo, I don't it being displayed even though it's taking a lot of room.

What's strange though is it is displayed for only two types of credentials! Why is it not the case on the others?

@cmcWebCode40 @RochelleBondoc

**Comment by cmcWebCode40** [comment]
Hi @aurelticot, 
just checking the `didJWTVC` displays for all credentials, because when a VC. is being created,  in our VC lib the `createCredentialJWT()` generates the `didJwtVc` value.

please can you point me to the credential that VC doesn't display?

**Comment by cmcWebCode40** [comment]
> I said that based on Rochelle comment above

ok
